### ISSUE TITLE
Object 'fn' not found

### ISSUE THREAD

**Issue by brucewayne521** [tanlabcode/CytoTalk#3]
Dear developer：
  Excellent tool for single-cell RNAseq cell-cell interaction analysis！
  However，I encounter an Error "Error in CytoTalk::run_cytotalk(lst_scrna, type_a, type_b) : object 'fn' not found." during "[7 / 8] (11:21:34) Generate network output..." step. How should I deal with it?
  My code exactly followed the vignette.

**Comment by brucewayne521** [comment]
With:
In addition: Warning messages:
1: In xtfrm.data.frame(x) : cannot xtfrm data frames
2: In sprintf(FORM_EDGE, df_net_sub$node1, df_net_sub$node2, c1, c2,  :
  one argument not used by format '"%s" -> "%s" [href = "https://hagrid.dbmi.pitt.edu/wiki-pi/index.php/search?q=%s+%s" penwidth = %s]'
3: In sprintf(FORM_EDGE, df_net_sub$node1, df_net_sub$node2, c1, c2,  :
  one argument not used by format '"%s" -> "%s" [href = "https://hagrid.dbmi.pitt.edu/wiki-pi/index.php/search?q=%s+%s" penwidth = %s]'
4: In sprintf(FORM_EDGE, df_net_sub$node1, df_net_sub$node2, c1, c2,  :
  one argument not used by format '"%s" -> "%s" [href = "https://hagrid.dbmi.pitt.edu/wiki-pi/index.php/search?q=%s+%s" penwidth = %s]'
5: In sprintf(FORM_EDGE, df_net_sub$node1, df_net_sub$node2, c1, c2,  :
  one argument not used by format '"%s" -> "%s" [href = "https://hagrid.dbmi.pitt.edu/wiki-pi/index.php/search?q=%s+%s" penwidth = %s]'

**Comment by shanedrabing** [comment]
Hello @brucewayne521, I just checked this issue out. Thanks for raising it, because I was able to find the stray line that was causing you an error, as well as correcting the `sprintf` call that made warnings, and even found a third bug. I feel ashamed that 3 bugs were live on the repo, but the code was just recently re-worked.

Do you mind reinstalling from source and trying again?

**Comment by brucewayne521** [comment]
Hello @shanedrabing, thank you for your timely reply! Now it is running very well. Really appreciate your help!
