### ISSUE TITLE
please run CMD build/CMD check

### ISSUE THREAD

**Issue by vjcitn** [tanlabcode/CytoTalk#4]
```
* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
  ...
--- re-building ‘cytotalk_guide.Rmd’ using rmarkdown
File ../docs/cytotalk_diagram.png not found in resource path
```
you will have to put this in inst for it to be available after R CMD install

**Comment by shanedrabing** [comment]
@vjcitn 
I couldn't figure out how to access a path from the vignette to the `inst` folder, so I opted to use URLs to the GitHub images instead. Is this an acceptable fix?
