### ISSUE TITLE
Replacement length issue while running "run_cytotalk"

### ISSUE THREAD

**Issue by Lakshya3141** [tanlabcode/CytoTalk#5]
Hello! I am trying to run CytoTalk to find out cell-cell interactions in my data obtained via Seurat. I am using a matrix of scaled data of 1315 cells (columns) across 18838 genes (rows). For the same, I have provided a cell_type vector which has the clusters assigned from previous processing (of length 1315).
Upon running the function, an error pops up, which is given below. I have also attached the dimensions of variables and codes used.

mat <- as.matrix(dummy@assays$RNA@scale.data)
cell_types <- as.vector(as.character(dummy$clusters))
lst_scrna <- CytoTalk:::new_named_list(mat, cell_types)
results <- CytoTalk::run_cytotalk(lst_scrna, "3", "7")

![image](https://user-images.githubusercontent.com/67403951/154242238-fb708047-e6f2-4ac1-a456-df8f35a3a87f.png)

Could you provide insights on how to cure this issue? I can't seem to figure out the error here.

**Comment by shanedrabing** [comment]
Does your matrix have rownames set to gene names? Check the man page for this function with `?CytoTalk::run_cytotalk`. Your gene names should be found in `CytoTalk::pcg_human`.

**Comment by shanedrabing** [comment]
@Lakshya3141 We may have found a solution, can you install from GitHub again and try running this once more?

**Comment by Lakshya3141** [comment]
@shanedrabing thanks for the prompt response. While the rownames are set to gene names (human symbols), there are some genes NOT present in 'CytoTalk::pcg_human'. To solve this, I subsetted the matrix to contain only rows available in the list you suggested.
Subsequent to this, I reinstalled the package from GitHub and tried it again. I still see the same error unfortunately :(

#My Code Snippet#
library(CytoTalk)
dummy <- subset(pbmc, subset = samples == 'b')
mat <- as.matrix(dummy@assays$RNA@scale.data)
cell_types <- paste0("cluster_",as.vector(as.character(dummy$clusters)))
common_genes <- intersect(CytoTalk::pcg_human,rownames(mat))
lst_scrna <- CytoTalk:::new_named_list(mat[common_genes,], cell_types)
table(lst_scrna$cell_types)
results <- CytoTalk::run_cytotalk(lst_scrna, "cluster_3", "cluster_7")

![image](https://user-images.githubusercontent.com/67403951/155307245-21c61a53-b94f-4199-aacb-f8d83e3e13d1.png)

**Comment by shanedrabing** [comment]
Is your input data privacy sensitive? If not, I can use your data to debug the program, that may be the fastest way for me to figure out what is still happening in that function...

**Comment by Lakshya3141** [comment]
@shanedrabing It is a little data privacy sensitive, but I think I can mask and send it to you? I would DM you for the same :)
