### ISSUE TITLE
invalid 'times' argument

### ISSUE THREAD

**Issue by AnneTalkington** [tanlabcode/CytoTalk#6]
Hi, I am interested in using CytoTalk with one of my data sets.

I have installed CytoTalk and all dependencies, and I am using input similar to CellPhoneDB (expression matrix in one file, metadata on cell type in a second file).  When I attempt to run the program with my data set, it throws the error "[1 / 8] (12:11:50) Preprocessing... Error in rep(0, m - 1) : invalid 'times' argument".  When I tried a subset of my data set, it ran through the first couple of steps, but failed to generate a gene relevance or prize for any of my nodes, instead returning a vector of NaNs.  It did compute edge cost.  From here, the program continued to run, but only identified a single node, which was not one of the potential nodes listed in my input, so I am unsure where this output came from.  Due to the lack of gene relevance values, I do not trust any output past the initial step.

In case it is helpful, I am running R version 4.1.0 and my expression data is a (relatively sparse) matrix of log-normalized TPMs that has been through quality control for cells, but not filtered to remove genes below a fixed expression threshold.  I am using the "human" values for pcg and lrp.  There is a chance that not all of the genes in my data set will be in your library because it contains some specific orfs.

Do you have any recommendations for how to resolve these errors?

Thank you for your help, and for making your program available.

**Comment by AnneTalkington** [comment]
I would like to add that the initial error appears to be thrown in the "nonselftalk" function.  Thank you.

**Comment by shanedrabing** [comment]
@AnneTalkington Thanks for pointing out this error! I just stumbled upon the same error, and it had to do with a the way `nonselftalk` fills in rows with only zeros. The indexing methods between base R `matrix` and the Matrix package class don't do well together.

Anyways, the bug should be fixed. Can you try again?

**Comment by AnneTalkington** [comment]
@shanedrabing Thank you, that seems to have fixed it!  It is almost running for me now, except the last step is returning the error: "[8 / 8] (14:36:42) Analyze pathways... Warning message: In xtfrm.data.frame(x) : cannot xtfrm data frames".  I wonder if it is a compatibility issue with certain packages?

**Comment by shanedrabing** [comment]
@AnneTalkington Looks instead to be a different in how R 4.1 changed code regarding the `order` function, breaking some code in the process... I'm on R 4.0.3, but really should update to make sure it works with newer versions. In the meantime, I tried converting all input to `order` functions with `as.numeric`, which I presume would fix this issue. You can try it now, but I'll get back to you once I update and test myself.

**Comment by AnneTalkington** [comment]
@shanedrabing Thank you for looking into it!  I tried reinstalling/ rerunning with the update and unfortunately it is still giving me the xtfrm error.

**Comment by shanedrabing** [comment]
@AnneTalkington Very sorry Anne, thought I caught the bug! Well, I know this isn't an option for all experimenters, but if you are able to provide your input data, that would be the fastest way for me to diagnose the issue. Otherwise, if you can get a more detailed traceback of the error from R (which can be difficult), that would be appreciated.

**Comment by AnneTalkington** [comment]
@shanedrabing I tried updating all of my packages again and that actually seemed to resolve it - odd, but I'm not complaining!  Now that I can visualize output, I am a bit confused about how the green arrows are being generated, since many of them are coming out of a receptor and into a ligand (which is opposite from both how the biological process occur, and the order the ligand-receptor pairs are listed in the pathways output table).  It is also generating blank, grey ovals in addition to the actual nodes (partial screenshot attached for my T cell sample).  If this is simply an issue of visualization, I can alter the images, but I wanted to bring it to your attention in case there is a larger issue blackboxed somewhere.  Thanks again for your help!
![image](https://user-images.githubusercontent.com/20506030/155785529-85336856-0336-4c83-87dd-bc8d954bb598.png)

**Comment by shanedrabing** [comment]
@AnneTalkington Not just a visualization error, or at least I think so. Both of these issues are legitimate errors from how you describe them, but I cannot check the correctness of the ligand-receptor pair file without knowing the origin of those green edges. The blank node and the node labeled "T" are very strange, never seen that before.

Again, these issues are hard to diagnose without the input data, with that I could investigate further, but otherwise I'm confused on how these are showing up in the graphs.

**Comment by AnneTalkington** [comment]
@shanedrabing I can send you a couple of files - is the gmail in your profile a good place?

**Comment by shanedrabing** [comment]
@AnneTalkington Sure thing, that'll do.

**Comment by AnneTalkington** [comment]
@shanedrabing Just sent!
